In [58]:
path_college = '../../capstone_project_1/college-passing-statistics'

In [59]:
%matplotlib inline
import pandas as pd
import statistics
import numpy as np
import os
import glob

In [60]:
college_passing = pd.concat(map(pd.read_csv, glob.glob(path_college + '/*.csv')),sort = True)

In [61]:
#split player names out
player_names = college_passing['Player']
player_names = player_names.iloc[:].str.split('*', n=1, expand=True)
player_names = player_names.iloc[:, 0].str.split('\\', n=1, expand = True)
player_names = player_names.drop([1], axis=1)
player_names = player_names.rename(columns={0:'Player'})

In [62]:
college_passing['Player'] = player_names['Player']

In [63]:
college_passing = college_passing.set_index(['Player']).sort_index()

In [64]:
college_passing

,AY/A,Att,Cmp,Conf,G,Int,Pct,Rate,Rk,School,TD,Y/A,YPC,Yds,rush_Att,rush_TD,rush_Yds
Player,,,,,,,,,,,,,,,,,
A.J. Doyle,3.8,235,128,MAC,11,11,54.5,99.1,101,Massachusetts,6,5.4,2.3,1274,65,0,151
A.J. Erdely,7.3,338,205,CUSA,13,4,60.7,131.8,70,UAB,16,6.9,2.7,2331,122,13,326
A.J. McCarron,8.3,328,219,SEC,13,5,66.8,147.3,24,Alabama,16,8.0,-0.7,2634,30,2,-22
A.J. McCarron,9.8,336,226,SEC,13,7,67.3,167.2,11,Alabama,28,9.1,-0.6,3063,34,0,-22
A.J. McCarron,10.8,314,211,SEC,14,3,67.2,175.3,4,Alabama,30,9.3,0.1,2933,49,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zach Smith,6.3,201,105,Big 12,9,8,52.2,118.9,59,Baylor,8,7.3,-2.6,1471,30,0,-79
Zach Terrell,9.5,391,262,MAC,13,9,67.0,162.5,9,Western Michigan,29,9.0,1.4,3522,77,3,107
Zach Terrell,5.6,251,133,MAC,9,8,53.0,110.7,88,Western Michigan,8,6.4,0.0,1602,42,0,0
Zach Terrell,9.5,368,250,MAC,13,10,67.9,164.4,3,Western Michigan,26,9.4,3.4,3443,78,3,264
Zach Terrell,10.6,377,263,MAC,14,4,69.8,175.2,5,Western Michigan,33,9.4,3.1,3533,80,7,249

In [70]:
#total td
qb_td = college_passing['TD']
qb_td = qb_td.groupby(qb_td.index).sum()
#total int
qb_int = college_passing['Int']
qb_int = qb_int.groupby(qb_int.index).sum()
#total yds
qb_yds = college_passing['Yds']
qb_yds = qb_yds.groupby(qb_yds.index).sum()
#total games
qb_games = college_passing['G']
qb_games = qb_games.groupby(qb_games.index).sum()
#total att
qb_att = college_passing['Att']
qb_att = qb_att.groupby(qb_att.index).sum()
#total cmp
qb_cmp = college_passing['Cmp']
qb_cmp = qb_cmp.groupby(qb_cmp.index).sum()

#rush Att
rush = college_passing['rush_Att']
rush = rush.groupby(rush.index).sum()

#rush TD
td = college_passing['rush_TD']
td = td.groupby(td.index).sum()

#rush yds
rush_yds = college_passing['rush_Yds']
rush_yds = rush_yds.groupby(rush_yds.index).sum()

In [74]:
#qb stats, replace necessary columns with totals
career_stats = college_passing.groupby(college_passing.index).mean().round(1)
career_stats['TD'] = qb_td
career_stats['Int'] = qb_int
career_stats['Yds'] = qb_yds
career_stats['G'] = qb_games
career_stats['Att']  = qb_att
career_stats['Cmp'] = qb_cmp
career_stats['rush_Att'] = rush
career_stats['rush_TD'] = td
career_stats['rush_Yds'] = rush_yds

In [76]:
career_stats = career_stats.drop(['Rk'], axis=1)

In [77]:
career_stats

,AY/A,Att,Cmp,G,Int,Pct,Rate,TD,Y/A,YPC,Yds,rush_Att,rush_TD,rush_Yds
Player,,,,,,,,,,,,,,
A.J. Doyle,3.8,235,128,11,11,54.5,99.1,6,5.4,2.3,1274,65,0,151
A.J. Erdely,7.3,338,205,13,4,60.7,131.8,16,6.9,2.7,2331,122,13,326
A.J. McCarron,9.6,978,656,40,15,67.1,163.3,74,8.8,-0.4,8630,113,3,-40
AJ Bush,5.0,217,117,10,10,53.9,108.5,6,6.5,5.3,1413,138,8,733
Aaron Murray,9.3,1478,921,52,41,62.4,158.6,121,8.9,1.4,13166,286,16,396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zach Frazer,4.8,261,136,11,6,52.1,99.7,5,5.5,0.5,1425,29,0,14
Zach Maynard,6.7,1080,629,35,37,58.4,127.4,47,7.3,1.7,7898,269,8,446
Zach Mettenberger,9.0,648,399,25,15,61.8,149.9,34,8.9,-4.2,5691,81,0,-341
Zach Smith,7.1,826,467,31,24,56.2,130.1,40,7.6,-1.6,6276,130,1,-201
Zach Terrell,8.8,1387,908,49,31,64.4,153.2,96,8.6,2.0,12100,277,13,620

In [78]:
career_stats.to_csv(path_college+'college-passing.csv')